[project]
name = "quantlib-python"
version = "0.1.0"
dependencies = [
    "polars==1.31.0",
    "pydantic==2.11.7",
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.1",
    "coverage==7.10.1"
]

[tool.uv]
